create database java_mobile;
use java_mobile;
CREATE TABLE USERS (
       USER_ID BIGINT NOT NULL AUTO_INCREMENT 
     , FIRST_NAME VARCHAR(50) NOT NULL
     , LAST_NAME VARCHAR(50) NOT NULL
	 , SEX CHAR(1) NOT NULL 
     , ROLE TINYINT NOT NULL DEFAULT 0
     , E_MAIL VARCHAR(100) NOT NULL	 
     , PASSWORD VARCHAR(50) NOT NULL
     , PHONE VARCHAR(20) NOT NULL
     , ADDRESS TEXT
	 , MOD_BY BIGINT NOT NULL DEFAULT 1
	 , CREATE_DATE TIMESTAMP NOT NULL DEFAULT NOW()
     , MOD_DATE TIMESTAMP NOT NULL  
     , PRIMARY KEY (USER_ID) 
); 

CREATE TABLE RESERVATION (
       RESERVATION_ID BIGINT NOT NULL AUTO_INCREMENT 
	 , USER_ID BIGINT NOT NULL
	 , RESERVATION_DATE TIMESTAMP NOT NULL
	 , COMMENT TEXT	 	 
	 , STATUS TINYINT NOT NULL DEFAULT 0
	 , RATING TINYINT
	 , FEEDBACK TEXT
	 , NBR_ROOMS MEDIUMINT NOT NULL   
	 , COST DOUBLE   NOT NULL
     , MOD_BY BIGINT NOT NULL
     , CREATE_DATE TIMESTAMP NOT NULL  DEFAULT NOW()
     , MOD_DATE TIMESTAMP NOT NULL
     , PRIMARY KEY (RESERVATION_ID)  
	 , INDEX (USER_ID)
     , CONSTRAINT FK_RESV_USER_1 FOREIGN KEY (USER_ID)
                  REFERENCES USERS (USER_ID)
				  
	 , CONSTRAINT FK_RESV_USER_2 FOREIGN KEY (MOD_BY)
                  REFERENCES USERS (USER_ID)
);

CREATE TABLE CONFIGURATION (
       CONFIGURATION_ID MEDIUMINT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(50) NOT NULL
     , VALUE VARCHAR(100)
     , DESCRIPTION TEXT
     , CREATE_DATE TIMESTAMP NOT NULL
     , MOD_DATE TIMESTAMP NOT NULL
     , MOD_BY BIGINT NOT NULL
     , PRIMARY KEY (CONFIGURATION_ID)
	 , CONSTRAINT FK_CONFIG_USER_1 FOREIGN KEY (MOD_BY)
                  REFERENCES USERS (USER_ID) 
	 , UNIQUE INDEX  (NAME ASC)
);