create database java_mobile;
use java_mobile;

INSERT INTO CONFIGURATION (CONFIGURATION_ID, NAME, VALUE, DESCRIPTION, CREATE_DATE,MOD_DATE,MOD_BY) VALUES 
(1, 'UNIT_PRICE', '200', 'PRIX UNITAIRE', NOW(), NOW(), 1) 